In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("Teen_Mental_Health_Dataset-selected-columns.csv")

In [3]:
df.head()

,age,gender,daily_social_media_hours,platform_usage,sleep_hours,screen_time_before_sleep,academic_performance,physical_activity,social_interaction_level,stress_level
0,14,male,7.9,Instagram,7.4,2.9,3.01,1.5,low,2
1,19,female,1.9,TikTok,8.0,2.9,3.22,0.8,high,8
2,17,female,1.3,Instagram,7.6,0.5,3.92,0.0,high,2
3,15,male,7.4,TikTok,6.9,1.6,3.48,0.8,medium,1
4,15,female,4.7,Both,4.9,3.0,2.37,1.4,medium,3

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1200 entries, 0 to 1199
Data columns (total 10 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   age                       1200 non-null   int64
 1   gender                    1200 non-null   object
 2   daily_social_media_hours  1200 non-null   float64
 3   platform_usage            1200 non-null   object
 4   sleep_hours               1200 non-null   float64
 5   screen_time_before_sleep  1200 non-null   float64
 6   academic_performance      1200 non-null   float64
 7   physical_activity         1200 non-null   float64
 8   social_interaction_level  1200 non-null   object
 9   stress_level              1200 non-null   int64
dtypes: float64(5), int64(2), object(3)
memory usage: 93.9+ KB

In [5]:
df.describe(include="all")

,age,gender,daily_social_media_hours,platform_usage,sleep_hours,screen_time_before_sleep,academic_performance,physical_activity,social_interaction_level,stress_level
count,1200.000000,1200,1200.000000,1200,1200.000000,1200.000000,1200.000000,1200.000000,1200,1200.000000
unique,NaN,2,NaN,3,NaN,NaN,NaN,NaN,3,NaN
top,NaN,male,NaN,Instagram,NaN,NaN,NaN,NaN,medium,NaN
freq,NaN,615,NaN,411,NaN,NaN,NaN,NaN,416,NaN
mean,15.928333,NaN,4.536667,NaN,6.449417,1.740333,2.990383,1.014500,NaN,5.445833
std,2.021947,NaN,2.029599,NaN,1.442677,0.716660,0.576758,0.582185,NaN,2.903290
min,13.000000,NaN,1.000000,NaN,4.000000,0.500000,2.000000,0.000000,NaN,1.000000
25%,14.000000,NaN,2.800000,NaN,5.200000,1.100000,2.500000,0.500000,NaN,3.000000
50%,16.000000,NaN,4.500000,NaN,6.500000,1.800000,2.990000,1.000000,NaN,5.000000
75%,18.000000,NaN,6.300000,NaN,7.600000,2.400000,3.480000,1.500000,NaN,8.000000
max,19.000000,NaN,8.000000,NaN,9.000000,3.000000,4.000000,2.000000,NaN,10.000000

In [6]:
df.isnull().sum()

age                         0
gender                      0
daily_social_media_hours    0
platform_usage              0
sleep_hours                 0
screen_time_before_sleep    0
academic_performance        0
physical_activity           0
social_interaction_level    0
stress_level                0
dtype: int64

In [7]:
df.duplicated().sum()

np.int64(0)

In [8]:
df.columns

Index(['age', 'gender', 'daily_social_media_hours', 'platform_usage',
       'sleep_hours', 'screen_time_before_sleep', 'academic_performance',
       'physical_activity', 'social_interaction_level', 'stress_level'],
      dtype='object')

# Average Social Media Platform Usage

In [9]:
df.groupby('platform_usage')['daily_social_media_hours'].mean().reset_index()

  platform_usage  daily_social_media_hours
0           Both                  4.518414
1      Instagram                  4.559367
2         TikTok                  4.531156

# Age Wise Stress Level

In [10]:
df.groupby('age')['stress_level'].mean().reset_index()

   age  stress_level
0   13      5.460000
1   14      6.176471
2   15      5.133333
3   16      5.453988
4   17      5.170588
5   18      5.203488
6   19      5.623457

# Age wise Average Social Media Hours

In [11]:
df.groupby('age')['daily_social_media_hours'].mean().reset_index()

   age  daily_social_media_hours
0   13                  4.511000
1   14                  4.350980
2   15                  4.717222
3   16                  4.636810
4   17                  4.763529
5   18                  4.242442
6   19                  4.516667

# Gender Wise Average Social Media Hours

In [12]:
df.groupby('gender')['daily_social_media_hours'].mean().reset_index()

   gender  daily_social_media_hours
0  female                  4.512991
1    male                  4.559187

# Age wise Average Sleep Hours

In [13]:
df.groupby('age')['sleep_hours'].mean().reset_index()

   age  sleep_hours
0   13     6.485500
1   14     6.315686
2   15     6.493889
3   16     6.485890
4   17     6.505882
5   18     6.359884
6   19     6.480864

# Gender Wise Average stress Level

In [14]:
df.groupby('gender')['stress_level'].mean().reset_index()

   gender  stress_level
0  female      5.422222
1    male      5.468293

# Gender Wise Sleep Hours

In [15]:
df.groupby('gender')['sleep_hours'].mean().reset_index()

   gender  sleep_hours
0  female     6.496410
1    male     6.404715

# Social Interaction Wise Average Stress Level

In [16]:
df.groupby('social_interaction_level')['stress_level'].mean().reset_index()

  social_interaction_level  stress_level
0                     high      5.512195
1                      low      5.349398
2                   medium      5.483173

In [17]:
from sqlalchemy import create_engine

# Mysql connection
username = "root"
password = "coder"
host = "localhost"
port = "3306"
database = "socialmedia"

engine = create_engine(f"mysql+pymysql://{username}:{password}@{host}:{port}/{database}")

table_name = "teen_analyze"
df.to_sql(table_name, engine , if_exists="replace", index=False)
pd.read_sql("Select*from teen_analyze limit 5;",engine)

,age,gender,daily_social_media_hours,platform_usage,sleep_hours,screen_time_before_sleep,academic_performance,physical_activity,social_interaction_level,stress_level
0,14,male,7.9,Instagram,7.4,2.9,3.01,1.5,low,2
1,19,female,1.9,TikTok,8.0,2.9,3.22,0.8,high,8
2,17,female,1.3,Instagram,7.6,0.5,3.92,0.0,high,2
3,15,male,7.4,TikTok,6.9,1.6,3.48,0.8,medium,1
4,15,female,4.7,Both,4.9,3.0,2.37,1.4,medium,3